[project]
name = "call-me-maybe"
version = "0.1.0"
description = "Add your description here"
authors = ["Joao Souza <jsouza@student.42lisboa.com>"]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flake8>=7.3.0",
    "flake8-pyproject>=1.2.4",
    "mypy>=2.1.0",
    "llm_sdk",
    "pydantic>=2.13.4",
    "uv>=0.11.21",
    "numpy>=2.2.6",
]

[tool.flake8]
extend-exclude = [
    ".venv",
	"llm_sdk",
	"moulinette"
]

[[tool.mypy.overrides]]
module = ["llm_sdk", "llm_sdk.*"]
ignore_errors = true

[tool.mypy]
exclude = "moulinette"

[tool.uv.sources]
llm-sdk = { path = "llm_sdk/" , editable = true }
