[project]
name = "call-me-maybe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flake8>=7.3.0",
    "flake8-pyproject>=1.2.4",
    "llm-sdk",
    "mypy>=2.1.0",
    "pydantic>=2.13.4",
    "uv>=0.11.21",
]

[tool.uv.sources]
llm-sdk = { path = "llm_sdk/dist/llm_sdk-0.1.0-py3-none-any.whl" }

[tool.flake8]
extend-exclude = [
    ".venv",
	"test.py",
	"llm_sdk"
]
